from time import sleep
from userbot import CMD_HELP, bot
from userbot.events import register
from telethon import events
import asyncio


@register(outgoing=True, pattern="^.sayang$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("I LOVEE YOUUU 💕")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💗💕")
        await e.edit("💘💞💕💗")
        await e.edit("SAYANG KAMU 💝💖💘")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💕💗")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("SELAMANYA 💕")
        await e.edit("💘💘💘💘")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("SAYANG")
        await e.edit("KAMU")
        await e.edit("I LOVE YOUUUU")
        await e.edit("MY BABY")
        await e.edit("💕💞💘💝")
        await e.edit("💘💕💞💝")
        await e.edit("GA DITERIMA🥺🥺💞")


@register(outgoing=True, pattern="^.gabut$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`PERNAAHHHHH KAHHH KAUUU MENGIRA`")
        await e.edit("`SEPEEERTIIIII APAAAA BENTUKKKKKKK CINTAAAA`")
        await e.edit("`RAMBUUUT WARNAAA WARNII`")
        await e.edit("`BAGAI GULALI`")
        await e.edit("`IMUUUTTTTT LUCUUU`")
        await e.edit("`WALAAUUUU TAK TERLALU TINGGI`")
        await e.edit("`GW GABUUTTTT`")
        await e.edit("`EMMMM BACOTNYA`")
        await e.edit("`GABUTTTT WOI GABUT`")
        await e.edit("🙈🙈🙈🙈")
        await e.edit("🙉🙉🙉🙉")
        await e.edit("🙈🙈🙈🙈")
        await e.edit("🙉🙉🙉🙉")
        await e.edit("`CILUUUKKK BAAAAA`")
        await e.edit("🙉🙉🙉🙉")
        sleep(2)
        await e.edit("🐢  TAK PERNAH KUSADARI 🧎")
        sleep(1)              
        await e.edit("🐢        AKU SEGILA INI             🚶")
        sleep(2)
        await e.edit("🐢     AKU HIDUP UNTUKMU                🚶")
        sleep(2)
        await e.edit("🐢   AKU MATI TANPAMU                🚶")
        sleep(2)
        await e.edit("🐢        ooooooo           🚶")
        sleep(5)
        await e.edit("🐢                  🚶")
        sleep(5)
        await e.edit("🐢         OOOOOOOOOOO        🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢     bodo        🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢    dahla        🚶")
        await e.edit("🐢     males     🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢  apa kau       🚶")
        await e.edit("🐢   capek   🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶      dorrrrr           🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶          matiiiiiii            🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶              astagfirullah            🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶               matiiiiiii yang dilakukan oleh             🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶             astagfirullah                  🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🚶                                 🐢")
        await e.edit("`AHHH MANTAP`")
        await e.edit("👌")
        await e.edit("🍌")
        await e.edit("👄")
        await e.edit("👅")
        await e.edit("💦")
        await e.edit("🥵")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢      BEGITU BANYAK HAL         🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢       YANG KU ALAMI      🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢     YANG KUTEMUI      🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢   SAAT BERSAMAMU KURASA SESIH    🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢  KURASA PAHIT  🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶  AIR MATA BOT   🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶      INI MENYANDARKANKU AKU ADALAH BOT   🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶           DAHLA                   🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🐢                       🚶")
        await e.edit("🐢                      🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢        🥺        🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢       🥺       🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢     🥺      🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶    🥺       🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("🐢                       🚶")
        await e.edit("🐢           🥺           🚶")
        await e.edit("🐢                     🚶")
        await e.edit("🐢                    🚶")
        await e.edit("🐢                   🚶")
        await e.edit("🐢                  🚶")
        await e.edit("🐢                 🚶")
        await e.edit("🐢                🚶")
        await e.edit("🐢               🚶")
        await e.edit("🐢              🚶")
        await e.edit("🐢             🚶")
        await e.edit("🐢            🚶")
        await e.edit("🐢           🚶")
        await e.edit("🐢          🚶")
        await e.edit("🐢         🚶")
        await e.edit("🐢        🚶")
        await e.edit("🐢       🚶")
        await e.edit("🐢      🚶")
        await e.edit("🐢     🚶")
        await e.edit("🐢    🚶")
        await e.edit("🐢   🚶")
        await e.edit("🐢  🚶")
        await e.edit("🐢 🚶")
        await e.edit("🐢🚶")
        await e.edit("🚶🐢")
        await e.edit("🚶 🐢")
        await e.edit("🚶  🐢")
        await e.edit("🚶   🐢")
        await e.edit("🚶    🐢")
        await e.edit("🚶     🐢")
        await e.edit("🚶      🐢")
        await e.edit("🚶       🐢")
        await e.edit("🚶        🐢")
        await e.edit("🚶         🐢")
        await e.edit("🚶          🐢")
        await e.edit("🚶           🐢")
        await e.edit("🚶            🐢")
        await e.edit("🚶             🐢")
        await e.edit("🚶              🐢")
        await e.edit("🚶               🐢")
        await e.edit("🚶                🐢")
        await e.edit("🚶                 🐢")
        await e.edit("🚶                  🐢")
        await e.edit("🚶                   🐢")
        await e.edit("🚶                    🐢")
        await e.edit("🚶                     🐢")
        await e.edit("🚶                      🐢")
        await e.edit("🚶                       🐢")
        await e.edit("🚶                        🐢")
        await e.edit("🚶                         🐢")
        await e.edit("🚶                          🐢")
        await e.edit("🚶                           🐢")
        await e.edit("🚶                            🐢")
        await e.edit("🚶                             🐢")
        await e.edit("🚶                              🐢")
        await e.edit("🚶                               🐢")
        await e.edit("🚶                                🐢")
        await e.edit("`GABUT`")


@register(outgoing=True, pattern='^.terkadang(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`Terkadang`")
    sleep(1)
    await typew.edit("`Mencintai Seseorang`")
    sleep(1)
    await typew.edit("`Hanya Akan Membuang Waktumu`")
    sleep(1)
    await typew.edit("`Ketika Waktumu Habis`")
    sleep(1)
    await typew.edit("`Tambah Aja 5000`")
    sleep(1)
    await typew.edit("`Bercanda`")
# Create by myself @localheart


@register(outgoing=True, pattern="^.maaf$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`maaf g dl` **ミ(ノ;_ _)ノ=3** ")


@bot.on(events.NewMessage(pattern=r"\.(.*)", outgoing=True))
async def _(event):

    if event.fwd_from:

        return

    animation_interval = 2

    animation_ttl = range(0, 11)

    input_str = event.pattern_match.group(1)

    if input_str == "cnta":

        await event.edit(input_str)

        animation_chars = [
            "`Connecting Ke Server Cinta`",
            "`Mencari Target Cinta`",
            "`Mengirim Cintaku.. 0%\n▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 4%\n█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 8%\n██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 20%\n█████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 36%\n█████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 52%\n█████████████▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim Cintaku.. 84%\n█████████████████████▒▒▒▒ `",
            "`Mengirim Cintaku.. 100%\n█████████CINTAKU███████████ `",
            f"`Cintaku Sekarang Sepenuhnya Terkirim Padamu, Dan Sekarang Aku Sangat Mencintai Mu, I Love You 💞`"]

        for i in animation_ttl:

            await asyncio.sleep(animation_interval)

            await event.edit(animation_chars[i % 11])



@register(outgoing=True, pattern='^.gombal(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`Hai, I LOVE YOU 💞`")
    sleep(1)
    await typew.edit("`I LOVE YOU SO MUCH!`")
    sleep(1)
    await typew.edit("`I NEED YOU!`")
    sleep(1)
    await typew.edit("`I WANT TO BE YOUR BOYFRIEND!`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💕💗`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💗💞`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💝💗`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💟💖`")
    sleep(1)
    await typew.edit("`I LOVEE YOUUUU💘💓`")
    sleep(1)
    await typew.edit("`Tapi Bo'ong`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.mantan(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`HAI MANTAN 🙂`")
    sleep(1)
    await typew.edit("`BERUBAH KARENA DIA`")
    sleep(1)
    await typew.edit("`ALASAN BANYAK`")
    sleep(1)
    await typew.edit("`SOK SIBUK`")
    sleep(1)
    await typew.edit("`JAWAB SINGKAT AMAT PAS BELUM PUTUS`")
    sleep(1)
    await typew.edit("`KAU PERGI DENGANNYA`")
    sleep(1)
    await typew.edit("`SUNGGUH TEGA`")
    sleep(1)
    await typew.edit("`AKU LIAT KAU BERDUAAN 🙃`")
    sleep(1)
    await typew.edit("`KAN KEINGET LAGI MASA SAKITNYA `")
    sleep(1)
    await typew.edit("`CUMA MANTAN AJAPUN 😂`")
    sleep(3)
    await typew.edit("`😁`")
    sleep(2)
    await typew.edit("`MANTAN NGEWE DIKOST`")
    sleep(2)
    await typew.edit("`😂`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.sedih(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`AKU SEDIH LOH `")
    sleep(1)
    await typew.edit("`KAMU SEDIH GAK?`")
    sleep(1)
    await typew.edit("`🥺🥺🥺`")
    sleep(1)
    await typew.edit("`🥺🥺`")
    sleep(1)
    await typew.edit("`😭🙃`")
    sleep(1)
    await typew.edit("`😭😭😭😭`")
    sleep(1)
    await typew.edit("`KAMU SUNGGUH TEGA`")
    sleep(1)
    await typew.edit("`AKU LIAT DIRIMU BERDUAAN😭`")
    sleep(1)
    await typew.edit("`BERSAMA HANDPHONE MU`")
    sleep(1)
    await typew.edit("`🙂🙃😭`")
    sleep(1)
    await typew.edit("`🥺😭🥺😭🥺😭🥺`")
# Create by myself @localheart

@register(outgoing=True, pattern='^.salam(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`Bismillah semoga dijawab salamnya`")
    sleep(1)
    await typew.edit("`Assalammuallaikum😊😊`")
# Create by myself @localheart


@register(outgoing=True, pattern="^.pantun$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        sleep(1)
        await e.edit("I LOVEE YOUUU 💕")
        sleep(2)
        await e.edit("IKAN HIU")
        sleep(2)
        await e.edit("MAKAN ULAR")
        sleep(2)
        await e.edit("EH SALAH APA YA LUPA TADI")
        sleep(2)
        await e.edit("EH GOBLOK")
        sleep(2)
        await e.edit("LU GOBLOK")
        sleep(1)
        await e.edit("BUAT PARA CEWEK ILOVE U😍")
        sleep(2)
        await e.edit("JANGAN PERNAH BILANG ADA YANG MENYAKITIMU")
        sleep(2)
        await e.edit("NANTI ORANG ITU AKAN HILANG")
        sleep(2)
        await e.edit("MAU GA JADI PACARKU")
        sleep(1)
        await e.edit("TETAP DISINI")
        sleep(2)
        await e.edit("TENAMANI AKU")
        sleep(1)
        await e.edit("SEPANJANG HIDUPKUUU")
        sleep(2)
        await e.edit("PERCAYALAH KUAKAN SELINGKUH 💕")
        sleep(1)
        await e.edit("MENDUAKANMU")
        sleep(2)
        await e.edit("SAYANG")
        sleep(1)
        await e.edit("KAMU")
        sleep(1)
        await e.edit("SAYANG")
        sleep(1)
        await e.edit("YOK GASKANNNN")
        sleep(2)
        await e.edit("I LOVE YOUUUU")
        sleep(1)
        await e.edit("MY BABY")
        sleep(1)
        await e.edit("💕💞💘💝")
        sleep(1)
        await e.edit("💘💕💞💝")
        sleep(1)
        await e.edit("MUACH MUACH😍😁💞")
# Create by myself @localheart


@register(outgoing=True, pattern='^.galau(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(5)
    await typew.edit("`🎸 JRENG JRENG JRENG `")
    sleep(3)
    await typew.edit("`KUMOHON KAU MENGERTI COBALAH KAU TAMBAHKAN HATI`")
    sleep(2)
    await typew.edit("`🎸 MUNGKIN DISAAT INI CINTA KITA SEDANG DIUJI `")
    sleep(2)
    await typew.edit("`TABAHKANLAH HATIMU OLEH SIKSA ORANG TUAMU `")
    sleep(2)
    await typew.edit("`🎸 KUYAKIN KITA MAMPU BILA KITA SALING MENUNGGU `")
    sleep(2)
    await typew.edit("`KU KAN SELALU SENANG MENUNGGU (WALAU HANYA KEKASIH GELAP MU`")
    sleep(2)
    await typew.edit("`🎸 SAD YA SEBAGAI SIMPANAN `")
    sleep(2)
    await typew.edit("`DAHLA MALES 🙂`")
# Create by myself @localheart


@register(outgoing=True, pattern='^melamarmu(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("` AKU ADALAH KAMU  `")
    sleep(1)
    await typew.edit("`AKU INGIN MENJADI TEMAN HIDUP UNTUKMU`")
    sleep(2)
    await typew.edit("` MAU GAK KALAU GAK MAU AKU PAKSA `")
    sleep(2)
    await typew.edit("`WALAUPUN DI PAKSA TIDAK ENAK`")
    sleep(3)
    await typew.edit("`😄`")
    sleep(2)
    await typew.edit("`BISMILAH`")
    sleep(3)
    await typew.edit("`KUCINTAI DIRIMU SEKARANG DENGAN SAH`")
    sleep(1)
    await typew.edit("`DILAN 1990`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.kntl(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`SI KONTOL`")
    sleep(2)
    await typew.edit("`SE KONTOLNYA KONTOL`")
    sleep(3)
    await typew.edit("`LEBIH MENGONTOL`")
    sleep(4)
    await typew.edit("`SIKONTOL`")
# Create by myself @localheart


CMD_HELP.update({
    "animasiyznwa":
    "•   **Syntax**: .sayang\
    \n•**Function**: terkadang\
    \n\n   •**Syntax**: .maaf\
    \n•**Function**: .cinta\
    \n\n   •**Syntax**: .cnta\
    \n•**Function**: mengirim cintamu ke seseorang\
    \n\n   •**Syntax**: .sayang\
    \n•**Function**: untuk jadi buaya\
    \n\n   •**Syntax**: .kntl\
    \n•**Function**: .kntl."
})
